import type { Listing, User, ViewingRequest, Host } from './types';

export const propertyTypes: string[] = [
  'Apartment',
  'House',
  'Cottage',
  'Townhouse',
];

export const amenitiesList: string[] = [
  'Wi-Fi',
  'Kitchen',
  'Washing machine',
  'Air conditioning',
  'Parking',
  'Swimming pool',
  'Gym',
  'Balcony',
  'Solar power',
  'Borehole',
  'Security',
  'Garden'
];

const hosts: { [key: string]: Host } = {
  'host-1': {
    id: 'host-1',
    name: 'Tendai Moyo',
    avatarUrl: 'https://i.pravatar.cc/150?u=tendai',
    isVerified: true,
  },
  'host-2': {
    id: 'host-2',
    name: 'Chipo Banda',
    avatarUrl: 'https://i.pravatar.cc/150?u=chipo',
    isVerified: false,
  },
  'host-3': {
    id: 'host-3',
    name: 'Farai Zulu',
    avatarUrl: 'https://i.pravatar.cc/150?u=farai',
    isVerified: true,
  },
};

export const listings: Listing[] = [
  {
    id: 'listing-1',
    title: 'Modern 2-Bed Apartment in Avondale',
    address: { city: 'Harare', country: 'Zimbabwe' },
    photos: ['https://images.pexels.com/photos/106399/pexels-photo-106399.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2', 'https://images.pexels.com/photos/276724/pexels-photo-276724.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2'],
    pricePerMonth: 850,
    bedrooms: 2,
    bathrooms: 2,
    propertyType: 'Apartment',
    amenities: ['Wi-Fi', 'Kitchen', 'Parking', 'Security', 'Solar power', 'Borehole'],
    description: 'A stunning, newly-renovated 2-bedroom apartment located in the heart of Avondale. Comes with reliable solar power and borehole water, ensuring you are never affected by utility shortages. Perfect for young professionals or a small family.',
    isAvailable: true,
    host: hosts['host-1'],
    rating: 4.8,
    reviewCount: 25,
    reviews: [
      { id: 'review-1', reviewer: { name: 'Tafadzwa', avatarUrl: 'https://i.pravatar.cc/150?u=tafadzwa' }, createdAt: 'June 2024', content: 'Great location and a very responsive host. The backup power and water were a lifesaver!' },
      { id: 'review-2', reviewer: { name: 'Linda', avatarUrl: 'https://i.pravatar.cc/150?u=linda' }, createdAt: 'May 2024', content: 'Clean, modern, and comfortable. Highly recommend.' },
    ],
    houseRules: ['No smoking', 'No pets', 'No parties or events'],
    features: ['Solar Inverter', 'Backup Water Tank'],
    analytics: { viewCount: 1250, inquiryCount: 45 },
    isFeatured: true,
  },
  {
    id: 'listing-2',
    title: 'Cozy Family Home in Borrowdale',
    address: { city: 'Harare', country: 'Zimbabwe' },
    photos: ['https://images.pexels.com/photos/186077/pexels-photo-186077.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2', 'https://images.pexels.com/photos/259588/pexels-photo-259588.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2'],
    pricePerMonth: 1500,
    bedrooms: 4,
    bathrooms: 3,
    propertyType: 'House',
    amenities: ['Wi-Fi', 'Kitchen', 'Parking', 'Security', 'Swimming pool', 'Garden', 'Borehole'],
    description: 'Spacious and secure family home in the serene suburb of Borrowdale. Features a large garden, swimming pool, and excellent security. Ideal for families looking for comfort and tranquility.',
    isAvailable: true,
    host: hosts['host-2'],
    rating: 4.6,
    reviewCount: 18,
    reviews: [],
    houseRules: ['Pets allowed upon request', 'No loud music after 10 PM'],
    features: ['Electric Fence', 'Double Lock-up Garage'],
    analytics: { viewCount: 2100, inquiryCount: 62 },
    isFeatured: true,
  },
  {
    id: 'listing-3',
    title: 'Charming 1-Bed Cottage',
    address: { city: 'Bulawayo', country: 'Zimbabwe' },
    photos: ['https://images.pexels.com/photos/209296/pexels-photo-209296.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2', 'https://images.pexels.com/photos/271624/pexels-photo-271624.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2'],
    pricePerMonth: 280,
    bedrooms: 1,
    bathrooms: 1,
    propertyType: 'Cottage',
    amenities: ['Wi-Fi', 'Kitchen', 'Parking', 'Garden'],
    description: 'A quiet and private cottage perfect for a single person or couple. Located in a peaceful neighborhood with a beautiful shared garden.',
    isAvailable: false,
    host: hosts['host-3'],
    rating: 4.9,
    reviewCount: 32,
    reviews: [],
    houseRules: ['No smoking'],
    features: [],
    analytics: { viewCount: 980, inquiryCount: 80 },
  },
   {
    id: 'listing-4',
    title: 'Modern Townhouse with Great Views',
    address: { city: 'Harare', country: 'Zimbabwe' },
    photos: ['https://images.pexels.com/photos/323780/pexels-photo-323780.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2', 'https://images.pexels.com/photos/1396122/pexels-photo-1396122.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2'],
    pricePerMonth: 1100,
    bedrooms: 3,
    bathrooms: 2,
    propertyType: 'Townhouse',
    amenities: ['Wi-Fi', 'Kitchen', 'Parking', 'Security', 'Balcony', 'Solar power'],
    description: 'A beautiful and secure townhouse in a well-managed complex. Offers great views from the balcony and comes with a reliable solar power system. Close to shops and schools.',
    isAvailable: true,
    host: hosts['host-1'],
    rating: 4.7,
    reviewCount: 15,
    reviews: [],
    houseRules: ['No pets', 'Respect complex rules'],
    features: ['Communal Borehole', '24/7 Security'],
    analytics: { viewCount: 1500, inquiryCount: 33 },
  },
];

export const users: { [key: string]: User } = {
  tenant: {
    id: 'user-tenant-1',
    name: 'Rudo Chen',
    role: 'tenant',
    avatarUrl: 'https://i.pravatar.cc/150?u=rudo',
    isVerified: true,
  },
  landlord: {
    id: 'user-landlord-1',
    name: 'Tendai Moyo',
    role: 'landlord',
    avatarUrl: 'https://i.pravatar.cc/150?u=tendai',
    isVerified: true,
    subscriptionStatus: 'active',
    subscriptionExpiry: 'August 25, 2024',
  },
};

export const viewingRequests: ViewingRequest[] = [
    {
        id: 'req-1',
        propertyId: 'listing-1',
        tenant: {
            id: 'tenant-2',
            name: 'John Doe',
            avatarUrl: 'https://i.pravatar.cc/150?u=john',
        },
        landlordId: hosts['host-1'].id,
        dateTime: { date: 'Tomorrow', timeSlot: 'Afternoon' },
        message: 'Hello, I am very interested in this apartment. Is it possible to view it tomorrow?',
        status: 'pending',
    },
    {
        id: 'req-2',
        propertyId: 'listing-4',
        tenant: {
            id: 'tenant-3',
            name: 'Jane Smith',
            avatarUrl: 'https://i.pravatar.cc/150?u=jane',
        },
        landlordId: hosts['host-1'].id,
        dateTime: { date: 'Today', timeSlot: 'Morning' },
        status: 'confirmed',
    },
];
